default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tokudome
  password: 
  host: localhost
  timeout: 5000

development:
  <<: *defautl
  database: SampleApp2_development

test:
  <<: *default
  database: SampleApp2_test

production:
  <<: *default
  database: SampleApp2_production