default: &default
  adapter: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: SampleApp2_development

test:
  <<: *default
  database: SampleApp2_test

production:
  <<: *default
  database: db/production.sqlite3